import base from "./base.js";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";

/**
 * ESLint config for Next.js applications.
 *
 * Note: We do NOT use `eslint-config-next` directly because it depends on
 * legacy `.eslintrc` plumbing that is being phased out in ESLint 9. Instead
 * we wire up the React + React Hooks plugins manually here, and rely on
 * `next lint` for Next-specific checks when desired.
 */
export default [
  ...base,
  {
    // Next.js writes a triple-slash reference into next-env.d.ts on every
    // boot. It's autogenerated and must not be edited; just exclude it.
    ignores: ["next-env.d.ts"],
  },
  {
    files: ["**/*.{ts,tsx,js,jsx}"],
    plugins: {
      react,
      "react-hooks": reactHooks,
    },
    languageOptions: {
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        console: "readonly",
        process: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        IndexedDB: "readonly",
        indexedDB: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        AbortController: "readonly",
        ReadableStream: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        crypto: "readonly",
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    settings: {
      react: { version: "detect" },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
    },
  },
];
